import { palette } from "../palette";

export const MuiButton = {
  styleOverrides: {
    // Name of the slot
    contained: {
      borderRadius: "4px",
      padding: "10px 10px",
      maxWidth: "380px",
      width: "100% ",
      height: 34,
      boxShadow: "none",
      color: "#fff",
      backgroundColor: palette.primary.main,
      fontFamily: "Poppins-Medium",
      fontSize: 14,
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "Bold",
      letterSpacing: 0.36,
      textTransform: "capitalize",
      "&:hover": {
        backgroundColor: palette.primary.main,
      },
      "&.Mui-disabled": {
        backgroundColor: `#013eb796 !important`,
        color: "#fff",
        opacity: 1,
      },
    },
    outlined: {
      padding: "15px 15px",
      maxWidth: "180px",
      minWidth: "20px",
      width: "100% ",
      height: 34,
      border: `1px solid ${palette.primary.gray}`,
      boxShadow: "none",
      borderRadius: "4px",
      color: palette.primary.gray,
      backgroundColor: "#fff",
      fontFamily: "Poppins-Regular",
      fontSize: 14,
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "Bold",
      letterSpacing: 0.36,
      textTransform: "capitalize",

      "&:hover": {
        backgroundColor: palette.primary.main,
        border: `1px solid #3f6dfd ${palette.primary.main}`,
        color: "#fff",
      },
      "&.Mui-disabled": {
        backgroundColor: "#D5D4DC !important",
        color: "#8B849B",
        opacity: 1,
      },
    },

    text: {
      textDecoration: "none",
      fontFamily: "Poppins-Regular",
      padding: "6px 0px",
      fontSize: 12,
      fontWeight: "normal",
      fontStretch: "normal",
      lineHeight: "normal",
      letterSpacing: "normal",
      fontStyle: "italic",
      textAlign: "left",
      color: palette.primary.dark,
      textTransform: "none",
      "&:hover": {
        textDecoration: "none",
        backgroundColor: "transparent",
      },
    },
    white: {
      padding: "18px 35px ",
      maxWidth: "243px",
      width: "100% ",
      height: 49,
      boxShadow: "rgba(1, 62, 183, 0.3) 5px 5px 10px",
      borderRadius: "10px",
      color: palette.white,
      backgroundColor: "#fff",
      fontFamily: "Poppins-Regular",
      fontSize: 18,
      fontWeight: "normal",
      fontStretch: "normal",
      fontStyle: "Bold",
      letterSpacing: 0.36,
      textTransform: "capitalize",
      "&:hover": {
        backgroundColor: "#fff",
      },
      "&.Mui-disabled": {
        backgroundColor: "#D5D4DC !important",
        color: "#8B849B",
        opacity: 1,
      },
    },

    activity: {
      padding: "0px",
      maxWidth: 120,
      width: "100%",
      height: 30,
      color: palette.white,
      background: "#0575E6",
      fontFamily: "Poppins-Medium",
      fontSize: 12,
      fontWeight: "normal",
      fontStretch: "normal",
      letterSpacing: 0.36,
      textTransform: "capitalize",
      "&:hover": {
        backgroundColor: "#3f6dfd",
        border: "1px solid #3f6dfd",
        color: "#fff",
      },
      "&.Mui-disabled": {
        backgroundColor: "#D5D4DC !important",
        color: "#8B849B",
        opacity: 1,
      },
    },
  },
};
